apiVersion: v1
kind: Pod
metadata:
  name: test-pd
  namespace: demo
spec:
  containers:
  - image: nginx
    name: test-container
    volumeMounts:
    - mountPath: /test-pd
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      # directory location on host
      path: /var/postgres-snapshots
      # this field is optional
      type: Directory